version: "3.9"

services:
    server:
        container_name: rembook_23
        image: rembook_23:prod
        build:
            context: .
            target: prod
        ports:
            - 3000:80
        restart: always
